# Основное
speed=1.5
save-position-on-quit=yes
save-position-on-quit=yes
vo=gpu-next
gpu-context=wayland 
interpolation=yes
tscale=oversample
deband=yes



# Шрифты
osd-font="JetBrains Mono Nerd Font Medium"
sub-font="JetBrains Mono Nerd Font Medium"
osd-font-size=30
sub-font-size=42
